server:
  persistentVolume:
    enabled: false
  service:
    type: NodePort
    nodePort: 30090

alertmanager:
  persistentVolume:
    enabled: false
  service:
    type: NodePort
    nodePort: 30091

serviceMonitors:
  - name: healthcare-app
    selector:
      matchLabels:
        app: healthcare-app
    endpoints:
      - port: http
        path: /actuator/prometheus
        interval: 15s
