apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  type: NodePort
  selector:
    app: healthcare-app
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30080
