apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
  labels:
    app: healthcare-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-app
        image: healthcare-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
